### ISSUE TITLE
ReactorNetty Benchmark Run

### ISSUE THREAD

**Issue by sharathsrinivasa** [sharathsrinivasa/wiremockserv#3]
-- Counters --------------------------------------------------------------------
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testBlockingGET.errors
             count = 0
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testMultiThreadedBlockingGET.errors
             count = 0
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testMultiThreadedBlockingLongLongPOST.errors
             count = 0
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testMultiThreadedBlockingShortShortPOST.errors
             count = 0
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testNonBlockingGET.errors
             count = 0
**com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testNonBlockingShortLongPOST.errors
             count = 9645**
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testNonBlockingShortShortPOST.errors
             count = 0
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.warmupBlocking.errors
             count = 0

-- Timers ----------------------------------------------------------------------
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testBlockingGET.timing
             count = 10000
         mean rate = 2.78 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.01 calls/second
    15-minute rate = 37.04 calls/second
               min = 0.21 milliseconds
               max = 3.01 milliseconds
              mean = 0.42 milliseconds
            stddev = 0.22 milliseconds
            median = 0.34 milliseconds
              75% <= 0.45 milliseconds
              95% <= 0.83 milliseconds
              98% <= 1.00 milliseconds
              99% <= 1.12 milliseconds
            99.9% <= 2.61 milliseconds
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testMultiThreadedBlockingGET.timing
             count = 10000
         mean rate = 2.78 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.01 calls/second
    15-minute rate = 37.25 calls/second
               min = 1.13 milliseconds
               max = 45.27 milliseconds
              mean = 14.38 milliseconds
            stddev = 7.20 milliseconds
            median = 13.74 milliseconds
              75% <= 16.66 milliseconds
              95% <= 27.53 milliseconds
              98% <= 36.16 milliseconds
              99% <= 41.88 milliseconds
            99.9% <= 44.04 milliseconds
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testMultiThreadedBlockingLongLongPOST.timing
             count = 10000
         mean rate = 2.79 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.00 calls/second
    15-minute rate = 3.49 calls/second
               min = 142.40 milliseconds
               max = 1691.50 milliseconds
              mean = 366.98 milliseconds
            stddev = 109.76 milliseconds
            median = 339.53 milliseconds
              75% <= 433.70 milliseconds
              95% <= 541.03 milliseconds
              98% <= 588.67 milliseconds
              99% <= 614.85 milliseconds
            99.9% <= 1602.50 milliseconds
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testMultiThreadedBlockingShortShortPOST.timing
             count = 10000
         mean rate = 2.78 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.01 calls/second
    15-minute rate = 37.25 calls/second
               min = 3.63 milliseconds
               max = 52.14 milliseconds
              mean = 16.90 milliseconds
            stddev = 6.73 milliseconds
            median = 15.89 milliseconds
              75% <= 19.31 milliseconds
              95% <= 29.46 milliseconds
              98% <= 38.23 milliseconds
              99% <= 42.12 milliseconds
            99.9% <= 51.98 milliseconds
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testNonBlockingGET.timing
             count = 10000
         mean rate = 2.78 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.01 calls/second
    15-minute rate = 37.25 calls/second
               min = 8.29 milliseconds
               max = 817.87 milliseconds
              mean = 507.06 milliseconds
            stddev = 231.88 milliseconds
            median = 566.64 milliseconds
              75% <= 696.08 milliseconds
              95% <= 801.09 milliseconds
              98% <= 814.75 milliseconds
              99% <= 817.20 milliseconds
            99.9% <= 817.83 milliseconds
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testNonBlockingShortLongPOST.timing
             count = 9998
         mean rate = 2.82 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.00 calls/second
    15-minute rate = 1.48 calls/second
               min = 143.63 milliseconds
               max = 61100.44 milliseconds
              mean = 57818.18 milliseconds
            stddev = 5008.18 milliseconds
            median = 58146.91 milliseconds
              75% <= 59365.67 milliseconds
              95% <= 60579.71 milliseconds
              98% <= 60810.49 milliseconds
              99% <= 61000.01 milliseconds
            99.9% <= 61100.44 milliseconds
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testNonBlockingShortShortPOST.timing
             count = 10000
         mean rate = 2.82 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.01 calls/second
    15-minute rate = 38.94 calls/second
               min = 5.82 milliseconds
               max = 1041.45 milliseconds
              mean = 578.72 milliseconds
            stddev = 268.05 milliseconds
            median = 580.89 milliseconds
              75% <= 799.81 milliseconds
              95% <= 993.86 milliseconds
              98% <= 1020.51 milliseconds
              99% <= 1039.76 milliseconds
            99.9% <= 1040.52 milliseconds
com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.warmupBlocking.timing
             count = 200
         mean rate = 0.06 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.00 calls/second
    15-minute rate = 0.74 calls/second
               min = 1137.88 milliseconds
               max = 1205.75 milliseconds
              mean = 1176.18 milliseconds
            stddev = 19.16 milliseconds
            median = 1178.24 milliseconds
              75% <= 1193.96 milliseconds
              95% <= 1203.08 milliseconds
              98% <= 1203.52 milliseconds
              99% <= 1204.87 milliseconds
            99.9% <= 1205.75 milliseconds

**Comment by sharathsrinivasa** [comment]
In the case of `com.ss.benchmark.httpclient.reactornetty.ReactorNettyHCPerformanceTests.testNonBlockingShortLongPOST.errors
count = 9645`, I observed following errors.

Please see these files for more information:
[serverErrors.txt](https://github.com/sharathsrinivasa/httpclientbenchmark/files/2681983/serverErrors.txt)
[clientErrors.txt](https://github.com/sharathsrinivasa/httpclientbenchmark/files/2681984/clientErrors.txt)

**Server side errors observed:**

```
21:43:47.047Z [qtp498793138-113] WARN  o.e.j.s.HttpChannel - /echodelayserv/echo/long
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:213)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:149)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:363)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:110)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.writeAndTranslateExceptions(WireMockHandlerDispatchingServlet.java:217)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.applyResponse(WireMockHandlerDispatchingServlet.java:207)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet$ServletHttpResponder.respondTo(WireMockHandlerDispatchingServlet.java:171)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet$ServletHttpResponder.respondSync(WireMockHandlerDispatchingServlet.java:138)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet$ServletHttpResponder.respond(WireMockHandlerDispatchingServlet.java:132)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:68)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:108)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:529)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 common frames omitted
21:43:47.047Z [qtp498793138-154] WARN  o.e.j.s.HttpChannel - Could not send response error 500: java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
```

**Client Side Errors:**
```
21:43:52.052Z [reactor-http-nio-7] ERROR c.s.b.h.r.ReactorNettyHCPerformanceTests - Failed : 552
reactor.netty.http.client.HttpClientOperations$PrematureCloseException: Connection prematurely closed BEFORE response
21:43:52.052Z [reactor-http-nio-7] ERROR c.s.b.h.r.ReactorNettyHCPerformanceTests - Failed : 516
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sharathsrinivasa** [comment]
Closing in favor of https://github.com/sharathsrinivasa/httpclientbenchmark/issues/11. These metrics are collected before massive refactoring of this benchmark. https://github.com/sharathsrinivasa/httpclientbenchmark/pull/9
